Correct wrong RNA path to Pose Bone Select property (#577)
before it would erroneously point to pose.bone.bone.select, corrected to point towards pose.bone.select

console error:
```
Python: Traceback (most recent call last):
  File "/Users/zophiekat/Library/Application Support/Blender/5.1/extensions/blender_org/pose_shape_keys/ops.py", line 1041, in execute
    driving_channels = self.get_driving_channels(context)
  File "/Users/zophiekat/Library/Application Support/Blender/5.1/extensions/blender_org/pose_shape_keys/ops.py", line 951, in get_driving_channels
    if self.only_selected and not pb.bone.select:
                                  ^^^^^^^^^^^^^^
AttributeError: 'Bone' object has no attribute 'select'

```

notice how the `pb` variable is followed by `bone` which will point towards the bone instead of the pose bone, since `pb` = `pose.bone` resulting in `pose.bone.bone`

Reviewed-on: https://projects.blender.org/studio/blender-studio-tools/pulls/577